// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jokslxzxdjmsykfqnzmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impva3NseHp4ZGptc3lrZnFuem13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjM3NDMsImV4cCI6MjA3MDgzOTc0M30.rrWLBMyouNssPwCTh7bsefhTLZBfbRsPINg_pU_Cfq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});